#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 15 18:23:51 2018

@author: aleksandradooley
"""

# censor words
def censor(text, word):
    words = text.split()
    result = ''
    stars = '*' * len(word)
    count = 0
    for i in words:
        if i == word:
            words[count] = stars
        count += 1
    result =' '.join(words)

    return result

print censor("This coding language is difficult", "language")

# lol this is me knowing I may not be one of those that naturally understands this mess
#wooh!
