#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 15 19:07:52 2018

@author: aleksandradooley
"""

# counting the number of times that something appears in a list

def count(sequence, item):
  count = 0
  for i in sequence:
    if i == item:
      count += 1
  return count

print count(["dogs", "cats", "dogs", "lizards", "cats", "dogs", "dogs", "chickens"], "dogs")
    