#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 18 09:07:00 2018

@author: aleksandradooley
"""

def purify(lst):
    res = []
    for i in lst:
        if i % 2 == 0:
            res.append(i)
    return res

print purify([1,2,3,4,5,6])

def product(lst):
  result = 1
  for i in range(0,len(lst)):
    result *= lst[i]
  return result

print product([1,2,3])

# which is different than the answer that they give but works
#here is codecademy's answer

def prod(list):
    total = 1
    for num in list:
        total = total * num
    return total