#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 20 14:54:44 2018

@author: aleksandradooley
"""

#n = [3, 5, 7]

#def print_list(x):
 # for i in range(0, len(x)):
  #  print x[i]
    
#print_list(n)


# exam statistics and how to print each item in the
# list on it's own line
grades = [100, 100, 90, 40, 80, 100, 85, 70, 90, 65, 90, 85, 50.5]

def print_grades(grades_input):
  for i in range(0, len(grades_input)):
    print grades_input[i]

print_grades(grades)


print "Let's compute some stats!"

# so to get the sum of the grades

def grades_sum(scores):
  result = 0
  for i in range(0, len(scores)):
    result += scores[i]
  return result
print grades_sum(grades)


#now to get the average

def grades_average(grades_input):
    sum_of_grades = grades_sum(grades_input)
    average = sum_of_grades / float(len(grades_input))
    return average

print grades_average(grades)

print "Time to conquer the variance!"

def grades_variance(scores):
    average = grades_average(scores)
    variance = 0
    for score in scores:
        variance += (average - score) ** 2
        result = variance/float(len(scores))
    return result
    
print grades_variance(grades)


def grades_std_deviation(variance):
    return variance ** 0.5

variance = grades_variance(grades)
# printing variance does what grades_variance does
print variance
print grades_std_deviation(variance)
