#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 18 10:19:46 2018

@author: aleksandradooley
"""

# delete duplicates in a list
def remove_duplicates(lst):
    new_list = []
    for i in lst:
        if i not in new_list:
            new_list.append(i)
    return new_list
    
print remove_duplicates([1, 1, 3, 4, 5, 3, 1])
        