#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  1 19:09:26 2018

@author: aleksandradooley
"""

# How to print a list with every character reversed
def reverse(text):
    word = ""
    l = len(text) - 1
    while l >= 0:
        word = word + text[l]
        l -= 1
    return word

print reverse("pickle")

def anti_vowel(text):
    t = ""
    for c in text:
        for i in "aeiouAEIOU":
            if c == i:
                c = ""
            else:
                c = c
        t = t + c
    return t

print anti_vowel("I love dogs! I love the ones that are french bulldogs more!")

# need to write notes out on this to be able to think through this process
