#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  1 09:16:48 2018

@author: aleksandradooley
"""

list_a = [3, 9, 17, 15, 19]
list_b = [2, 4, 8, 10, 30, 40, 50, 60, 70, 80, 90]

for a, b in zip(list_a, list_b):
    print max(a, b)
# doesn't go all the way through list b
    #so you can print the max of the items in a list using max(x, y)
    
# so make the else statement work
fruits = ['banana', 'apple', 'orange', 'tomato', 'pear', 'grape']

print 'You have...'
for f in fruits:
  if f == 'tomato':
    print 'A tomato is not a fruit!' # (It actually is.)
  print 'A', f
else:
  print 'A fine selection of fruits!'
  
  
dogs = ['beagle', 'shitzu', 'chihuahua', 'french bulldog', 'labradoodle' ]

print 'You could have ...'
for d in dogs:
    if d == 'chihuahua':
        print 'A chihuahua is not a dog! It is a rat!'
    print 'A', d
else:
    print 'What a great selection of dogs! Pick the french bulldog!'