#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu May 24 10:12:54 2018

@author: aleksandradooley
"""

#iterate through and concatenates all the sublists into one list


n = [[1, 2, 3], [4, 5, 6, 7, 8, 9]]
# Add your function here
def flatten(lists):
    results = []
    for numbers in lists:
        for number in numbers:
            results.append(number)
    return results
    
print flatten(n)

# so when they say iterate through lists call the looping variable numbers
# they want you to say for ___ in ___ or here the first blank is the looping
# variable and the second is what you want to iterate through
# then in the second you have to "iterate" through numbers 
