#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed May 30 21:28:51 2018

@author: aleksandradooley
"""

phrase = "A bird in the hand..."

# Add your for loop
for char in phrase:
    if char == "A" or char == 'a':
        print 'X' ,
    else:
        print char,

#Don't delete this print statement!
print