#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed May 30 21:05:06 2018

@author: aleksandradooley
"""

from random import randint

# Generates a number from 1 through 10 inclusive
random_number = randint(1, 10)

guesses_left = 3
# Start your game!
while guesses_left > 0:
    guess = int(raw_input("Your guess: "))
    if guess == random_number:
        print "You win!"
        break
    else:
        print "You lose."
        guesses_left -= 1