#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed May 30 21:18:13 2018

@author: aleksandradooley
"""

hobbies = []

# Add your code below!
for r in range(3):
    hobby = raw_input("Enter a hobby: ")
    hobbies.append(hobby)
    print hobbies