#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu May 24 10:09:52 2018

@author: aleksandradooley
"""

# how to print lists one after the other

m = [1, 2, 3]
n = [4, 5, 6]

def join_lists(x,y):
    return x + y

print join_lists(m, n)